"""Streamlit input workflow. Documents are previewed before any evaluation."""
import hashlib
import json
import re
from uuid import uuid4

import streamlit as st


def optional_number(value, integer=False):
    if not value.strip():
        return None
    if integer and not re.fullmatch(r"\d+", value.strip()):
        raise ValueError("Token usage must be a nonnegative whole number, or blank if unknown.")
    result = int(value) if integer else float(value)
    if result < 0 or (not integer and not __import__("math").isfinite(result)):
        raise ValueError("Reported latency and budgets must be finite nonnegative numbers, or blank if unknown.")
    return result


def render_input_form(api):
    st.subheader("Create an experiment")
    st.write("Paste an answer or upload one PDF/DOCX. Supporting evidence is supplied separately. No JSON is needed.")
    name = st.text_input("Experiment name", key="input_name", max_chars=10000)
    provenance = st.text_area("Provenance — where did these responses and measurements come from?", key="input_provenance", max_chars=10000)
    kind = st.selectbox("Data kind", ["synthetic", "recorded"], key="input_kind")
    question = st.text_area("Question / prompt", key="input_question", max_chars=10000)
    answer_mode = st.radio("AI answer input", ["Paste text", "Upload PDF/DOCX"], key="input_answer_mode")
    answer = st.text_area("AI answer (answer role)", key="input_answer", max_chars=100000) if answer_mode == "Paste text" else ""
    answer_file = st.file_uploader("AI answer document — answer role only", type=["pdf", "docx", "doc"], max_upload_size=5, key="input_answer_file") if answer_mode != "Paste text" else None
    st.caption("Legacy .doc must be converted to .docx. OCR is not available: scanned/image-only PDFs require OCR before upload. Maximum 5 MiB per file.")
    evidence = st.text_area("Supporting evidence (evidence role, optional)", key="input_evidence", max_chars=100000)
    evidence_files = st.file_uploader("Supporting evidence documents — evidence role only", type=["pdf", "docx", "doc"], max_upload_size=5, accept_multiple_files=True, key="input_evidence_files")
    st.caption("The answer document is never added to evidence. Supply distinct evidence documents explicitly. Up to 10 evidence inputs, including pasted evidence.")
    with st.expander("Optional evaluation settings and reported measurements"):
        record_id = st.text_input("Pairing / record ID (reuse for comparisons; blank generates one)", key="input_record_id")
        application_type = st.selectbox("Application type", ["llm", "rag", "agent", "research"], key="input_application_type")
        instructions = st.text_area("Explicit instructions (one per line)", key="input_instructions")
        reference = st.text_area("Reference answer", key="input_reference", max_chars=100000)
        reference_provenance = st.text_input("Reference provenance", key="input_reference_provenance", max_chars=10000)
        override_format = st.checkbox("Set format requirements for this experiment", key="input_override_format")
        st.caption("Server format settings apply unless the override is enabled. This option concerns the answer format; the platform input itself does not require JSON.")
        max_words = st.text_input("Maximum words (blank means no word limit)", key="input_max_words", disabled=not override_format)
        require_json = st.checkbox("Require the AI answer itself to be valid JSON", key="input_require_json", disabled=not override_format)
        repeated = st.text_area("Repeated answers (separate answers with a line containing ---)", key="input_repeated", max_chars=100000)
        st.caption("Supply independent answers to the same prompt/context/configuration. These are not generated by the platform.")
        latency = st.text_input("Actual reported response latency (ms; blank if unknown)", key="input_latency")
        budget = st.text_input("Latency budget (ms; blank uses server setting)", key="input_budget")
        input_tokens = st.text_input("Actual reported input tokens (blank if unknown)", key="input_input_tokens")
        output_tokens = st.text_input("Actual reported output tokens (blank if unknown)", key="input_output_tokens")
        total_tokens = st.text_input("Actual reported total tokens (blank if unknown)", key="input_total_tokens")
    fields = dict(name=name, provenance=provenance, data_kind=kind, question=question,
                  application_type=application_type, reference_answer=reference or None,
                  reference_provenance=reference_provenance or None,
                  instructions=[x.strip() for x in instructions.splitlines() if x.strip()])
    # A changed input invalidates the prepared snapshot; changing roles or a
    # filename cannot accidentally reuse text from a previous upload.
    raw = [fields, record_id, answer_mode, answer, evidence, override_format, max_words,
           require_json, repeated, latency, budget, input_tokens, output_tokens, total_tokens]
    for uploaded in ([answer_file] if answer_file else []) + list(evidence_files):
        raw.append([uploaded.name, hashlib.sha256(uploaded.getvalue()).hexdigest()])
    signature = hashlib.sha256(json.dumps(raw, sort_keys=True).encode()).hexdigest()
    if st.button("Prepare editable preview", key="prepare_preview"):
        st.session_state.pop("prepared_input", None)
        try:
            if not all(x.strip() for x in (name, provenance, question)):
                raise ValueError("Enter an experiment name, provenance and question.")
            if (answer_mode == "Paste text" and not answer.strip()) or (answer_mode != "Paste text" and answer_file is None):
                raise ValueError("Paste an AI answer or choose one answer document.")
            if len(evidence_files) + bool(evidence.strip()) > 10:
                raise ValueError("At most 10 evidence inputs are supported, including pasted evidence.")
            if bool(reference.strip()) != bool(reference_provenance.strip()):
                raise ValueError("Supply both the reference answer and its provenance.")
            usage = {"input_tokens": optional_number(input_tokens, True), "output_tokens": optional_number(output_tokens, True), "total_tokens": optional_number(total_tokens, True)}
            fields.update(response_latency_ms=optional_number(latency), latency_budget_ms=optional_number(budget),
                          token_usage=usage if any(v is not None for v in usage.values()) else None,
                          record_id=record_id.strip() or str(uuid4()),
                          repeated_responses=re.split(r"(?m)^---\s*$", repeated) if repeated.strip() else [])
            if any(not value.strip() for value in fields["repeated_responses"]):
                raise ValueError("Remove empty repeated-answer blocks.")
            if override_format:
                limit = optional_number(max_words, True)
                if limit == 0:
                    raise ValueError("The word limit must be at least 1.")
                fields["format"] = {"max_words": limit, "require_json": require_json}
            documents = []
            if answer_mode == "Paste text":
                response = api("POST", "/documents/paste", json={"role": "answer", "text": answer})
            else:
                response = api("POST", "/documents/extract", params={"filename": answer_file.name, "role": "answer"}, content=answer_file.getvalue())
            if response is None:
                return
            documents.append(response.json())
            if evidence.strip():
                response = api("POST", "/documents/paste", json={"role": "evidence", "text": evidence})
                if response is None:
                    return
                documents.append(response.json())
            for uploaded in evidence_files:
                response = api("POST", "/documents/extract", params={"filename": uploaded.name, "role": "evidence"}, content=uploaded.getvalue())
                if response is None:
                    return
                documents.append(response.json())
            if len({d["content_sha256"] for d in documents}) != len(documents):
                raise ValueError("Duplicate content is not allowed. The answer document must not also be supplied as evidence.")
            st.session_state["prepared_input"] = dict(signature=signature, fields=fields, documents=documents, key=str(uuid4()))
        except ValueError as exc:
            st.error(str(exc))
    draft = st.session_state.get("prepared_input")
    if not draft:
        return
    if draft["signature"] != signature:
        st.warning("Inputs changed. Prepare the preview again before evaluation; the previous preview cannot be submitted.")
        return
    st.subheader("Review and edit the prepared text")
    st.write("Compare every segment with the original document. Evaluation uses only the edited text below. Original extraction, filenames, roles and references are retained in the saved record.")
    edits = []
    with st.form("reviewed_experiment"):
        for document in draft["documents"]:
            st.text(f"Role: {document['role']} | {document['filename'] or 'Pasted text'}")
            for limitation in document["limitations"]:
                st.caption(limitation)
            values = {}
            for segment in document["segments"]:
                st.text(segment["reference"])
                with st.expander("Original extracted text — " + segment["reference"]):
                    st.code(segment["original_text"], language=None)
                    if segment["citation_markers"]:
                        st.text("Unresolved citation-like markers: " + ", ".join(segment["citation_markers"]))
                key = draft["key"] + document["id"] + segment["id"]
                values[segment["id"]] = st.text_area("Edited text — " + document["role"] + " / " + segment["reference"], value=segment["original_text"], key=key, max_chars=100000)
            edits.append({"extraction_id": document["id"], "edited_segments": values})
        roles = st.checkbox("I confirm the answer and evidence roles are correct", key="review_roles_" + draft["key"])
        reviewed = st.checkbox("I reviewed every segment against the original; the text is complete for evaluation", key="review_complete_" + draft["key"])
        submitted = st.form_submit_button("Evaluate and save reviewed experiment")
    if submitted:
        if not roles or not reviewed:
            st.error("Confirm roles and review completeness before evaluation.")
        else:
            response = api("POST", "/form-experiments", json={**draft["fields"], "documents": edits, "reviewed": reviewed, "roles_confirmed": roles})
            if response is not None:
                st.success("Saved experiment " + response.json()["id"])
