[theme]
base = "dark"
primaryColor = "#FED7B8"
backgroundColor = "#0E0406"
secondaryBackgroundColor = "#1A0509"
textColor = "#FFF5EE"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableStaticServing = true
